config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  
  # Defines the root path route ("/")
  root "allergens#index"
  resources :products
  resources :allergens
end

app/models/allergen.rb
class Allergen < ApplicationRecord
  #The model should be able to answer the question "Can user x do y to this object?"
  #When you write regular methods in the model those methods are all instance methods.  
  #In other words def some_method will be a method available on each retrieved record

# dependent: :destroy, rails will destroy all reactions associated with Allergen when its deleted
  has_many  :reactions, dependent: :destroy
  # A has_many :through association is often used to set up a many-to-many connection 
  # with another model (Reaction). This association indicates that the declaring model (Allergen) can be 
  # matched with zero or more instances of another model (Product) by proceeding through a third model (Reaction).
  has_many  :products, through: :reactions

  validates :category, presence: true
  #to validate more than one column (or more), you can add that to the scope
  validates :substances, presence: true, length: {minimum: 2}
  #Match any characters as few as possible until a ";" is found, without counting the ";".
  #validates :substances, format: { with: /.+?(?=;)/, :message => "must end with or be seperated by a ';'" }
  #validates :substances, format: { with: /.+?(?=;)/, :message => "must end with or be seperated by a ';'" }
  #validates_format_of :substances, :with => /.+?(?=;)/ ,
  #  :message => "must end with or be seperated by a ';'"
  #validates_format_of :substances, :with => /.+?(?=;)|\n/ ,
  #  :message => "must end with or be seperated by a ';' or a newline (return)"
  validates_format_of :substances, {:with =>  /.+?(?=;)|.+?(?=\n)/ ,
    :message => "must end with or be seperated by a ';' or a newline (return)"}


  #process user input substance string such that substances are seperated by ";"
  def substances=(value)
    processed_substance_str = process_new_allergen_entry(value)
    write_attribute(:substances, processed_substance_str)
  end

  def get_substances
    substances_array = self.substances.split(";")
    return substances_array
  end

  def process_new_allergen_entry(substances)

    substance_str = substances

    # if valid input
    if substances.include?(";") || substances.include?("\n")

      # seperate substances string into array elements using ";" and "newline"
      substances_array = substances.split(/;|\n/)

      # if only 1 substance in array add a an ";" to the end
      if substances_array.length == 1 
        substance_str = substances_array[0] + ";"
      else
        # delete any nill or all whitespace entries from array
        # and create a new string where ";" seperates each substance
        substance_str = substances_array.delete_if { |substance| substance.blank?}.join(";")
      end
    end

    return substance_str
  end

  # array of substances match the ingredient
  def matching_substances_to(ingredient)
    matching_substances = []
    # does ingredient match any substance in this allergen category 
    matching_substances = self.get_substances.select {|substance| 
        (ingredient.upcase.include?(substance.upcase) || substance.upcase.include?(ingredient.upcase))
      } 

    # matching substances should not inclue any matching whitespaces
    matching_substances = matching_substances.delete_if { |substance| substance.blank?}

    return matching_substances
  end

end

app/controllers/allergens_controller.rb
class AllergensController < ApplicationController
  # Use before_action to set up an instance variable for an action, 
  # in this case, call set_allergen before calling edit or destroy
  before_action :set_allergen, only: [:edit, :destroy, :update, :show]
  
# run 'rails routes' then add '_path' to the Prefix to get the url

#       Prefix Verb   URI Pattern                   Controller#Action
#---------------------------------------------------------------------
#    allergens GET    /allergens(.:format)          allergens#index
#              POST   /allergens(.:format)          allergens#create
# new_allergen GET    /allergens/new(.:format)      allergens#new
#edit_allergen GET    /allergens/:id/edit(.:format) allergens#edit
#     allergen GET    /allergens/:id(.:format)      allergens#show
#              PATCH  /allergens/:id(.:format)      allergens#update
#              PUT    /allergens/:id(.:format)      allergens#update
#              DELETE /allergens/:id(.:format)      allergens#destroy
#         root GET    /                             allergens#index

# The purpose of the controller is to manage the incoming request and session

# GET '/'
  def index
    # Allergens.all accesses model layer and stores result in an instance variable
    # which is passed to the view
    @allergens = Allergen.all
    # render 'allergens/index' happens by default at end of method
  end

  # GET '/allergens/new'
  def new
    # set up a new instance variable which is an active record object
    # and pass it to the 'new' template in "new.html.erb" 
    @allergen = Allergen.new
    # render 'allergens/new' happens by default at end of method
  end

  # GET '/allergens/:id/edit'
  def edit # url will be something like /allergens/"Formaldehyde"/edit, edit form will be rendered
    # @allergen = Allergen.find_by category: params[:id]... this is now done by set_allergen
    # render 'allergens/edit by default
  end

  # POST '/allergens'
  # the general pattern used in the action create that handles
  # submission of model-backed forms 
  def create 
    # the form displayed in "new.html.erb" is submitted to action='/allergens' 
    # using verb method="post" which is routed to allergens#create.
    # @allergen, is populated with values (params) submitted from the form
    @allergen = Allergen.new(allergen_params)

    if @allergen.save #returns "false" if it can't save
      flash[:success] = "Allergen was successfully created. Products re-checked for new Allergen."
      # redirect must be a url, can't render a view template
      # (add '_path' to the prefix to get the url)
      redirect_to allergen_path(@allergen) # index
    else
      # validation error occured. We must render to have access to 
      # "allergens.error.full_messages" array to display generated errors 
      render :new, status: :unprocessable_entity
      #render 'new'
    end
  end

  # PATCH '/allergens/:id'
  #the general pattern used in the action create that handles
  #submission of model-backed forms 
  def update # this is where the form displayed in 'edit' is submitted using verb "patch"
    # we have @allergen because set_allergen was invoked by before_action
    if @allergen.update(allergen_params)
      flash[:success] = "Allergen was successfully updated. Products re-checked to reflect update."
      redirect_to allergen_path(@allergen)
    else
      render :edit, status: :unprocessable_entity
      #render 'edit'
    end
  end

  # GET '/allergens/:id'
  def show
    #already have @allergen at this point because 'set_allergen' was invoked by before_action
    #render 'allergens/show' (show.html.erb) automatically called before exiting this method
  end

  # DELETE '/allergens/:id'
  def destroy
    # already have @allergen at this point because 'set_allergen' was invoked
    @allergen.destroy
    redirect_to allergens_path, status: :see_other, notice: "Allergen was successfully deleted"
  end

  private

  def set_allergen
    # ask ActiveRecord to find the Allergen object in the db using 
    # contains an integer ie: "12" or category ie: "Disperse Orange"
    !!params[:id].match(/^(\d)+$/) ?
      (@allergen = Allergen.find_by id: params[:id]) :
      (@allergen = Allergen.find_by category: params[:id])
  end

  def allergen_params
    # use strong parameters to expose the fields we're interested in
    # require top level key be allergen and allow changes to category, substances
    params.require(:allergen).permit(:category, :substances)
    # To permit all attributes params.require(:post).permit!
  end

end

app/views/allergens/_form.html.erb
<div><center>
  <div class='form-horizontal col-lg-6 col-lg-offset-3'>

    <%= form_for(@allergen, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group">
        <div class="col-lg-12">
          <%= f.label :category%>
        </div>
        <div class="col-lg-12">
          <%= f.text_field :category, id: "form-input", class: "form-control", placeholder: "Name of Allergen", autofocus: true %>
        </div>
      </div>
      <br>
      <div class="form-group">
        <div class="col-lg-12">
          <%= f.label :substances%>
        </div>
        <div class="col-lg-12">
          <%= f.text_area :substances, id: "form-textarea", class: "form-control", rows: "10", placeholder: 
"substance 1; substance 2; ...

substance 1
substanc 2..." %>

        </div>
      </div>  
      <br>
        <%= f.submit "Save", class: "btn btn-primary" %>
        <%= link_to "Back to Allergens List", allergens_path, class: "btn btn-xlarge btn-info" %>
    <% end %>
  </div>
</div></center>

app/views/allergens/edit.html.erb
<h1>
  <center>Edit Allergen
  </center>
</h1>

<%= render 'form'%>

<script>
  formStyle()
</script>

app/views/allergens/index.html.erb
<body style="background-color:lightcyan;">
<br>
<br>
  <h2><center>
  <%= link_to "Check a Product", new_product_path, class: "btn btn-xlarge btn-warning"%>

    <%= link_to "Add New Allergen", new_allergen_path,class: "btn btn-xlarge btn-info" %>
  </center></h2>
<br>

  <h1><center><strong>Current Allergens</strong></center></h1>

  <%= render partial: "shared/allergen", collection: @allergens, :locals => {search_item: ""} %>
</body>

app/views/allergens/new.html.erb
<body style="background-color:lightcyan;">
<h1>
  <center>Add a New Allergen</center>
</h1>

<small><center>
  <i><u>Enter ingredients seperated by a ";" (semi-colon) or a newline (return)</u></i>
</center></small>
<br>


<%= render 'shared/errors', obj: @allergen %>
<!-- would provide the @allergen object to the partial, available under the local variable obj -->
<%= render 'form'%>
</body>

app/views/allergens/show.html.erb
<body style="background-color:lightcyan;">
<br>
<br>

<%= render partial: 'shared/allergen', collection: Array(@allergen), :locals => {search_item: ""}  %>

<h2><center>
  <%= link_to "Back to Allergens List", allergens_path, class: "btn btn-xlarge btn-info"%>
</center></h2>
</body>