config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  
  # Defines the root path route ("/")
  root "allergens#index"
  resources :products
  resources :allergens
end

app/views/shared/_allergen.html.erb
 <!-- When a partial is called with a pluralized collection (ie: collection: @allergens), then the individual instances of the partial have access to the member of the collection being rendered via a variable named after the partial (allergen). In general 
if the partial is called with using "collection: somenames" and partial's name is "some_partial" then to access an individual instance of "somenames" would be "some_partial"-->

<style>
  table, th {
    border:5px solid black;
    background-color: lightcoral;
    text-align: center;
    margin-left: auto;
    margin-right: auto;
    padding-left: 20px;
    padding-right: 20px;
  }
  td {
    padding-left: 20px;
    padding-right: 20px;
    text-align: center;
    vertical-align: center;
  }
</style>

<% substances = allergen.get_substances %>
<table>
  <!-- Panel displaying allergen and substances -->
  <tr>
    <th>
      <h4><%= allergen.category %></h4>
      <h8><%= link_to 'Edit', edit_allergen_path(allergen) %></h8>
      <h8><%= link_to 'Show', allergen_path(allergen) %></h8>
      <h8><%= link_to "Delete", allergen_path(allergen), data: { turbo_method: "delete", turbo_confirm: "Are you sure?" } %></h8>
    </th>
  </tr>
  
    <% substances.each do |substance| %> 
      <% if substance.upcase.include?(search_item.upcase)%> 
         <tr style="background-color: pink;">
          <td>
            <%= highlight(substance, search_item) %>
          </td>
        </tr>
      <% end %>  
    <% end %>
</table>
<br>

app/views/shared/_errors.html.erb
<!-- Rails validations are triggered when the data submissions try to hit the database.The errors are saved on the model object. When there are validation errors, they are saved to the object.errors. We display the validation messages by referencing the object.errors.full_messages method like below. By using the full_messages method, the errors are displayed in a nice, readable sentence format. -->
<!-- Here, obj must be an active record object. -->

<% if obj.errors.any? %>
  <center><div style="background-color: lightpink; display: inline-block;">
    <h5>
      <%= pluralize(obj.errors.count, "error") %> prohibited this product from being saved/submitted:
    </h5>
      <% obj.errors.full_messages.each do |msg| %>
        <li>
          <%= msg %>
        </li>
      <% end %>
  </div></center>
<% end %>

app/views/shared/_form.html.erb
<!-- 
Model backed form helpers are tied to an object. There has to be a setter method, a virtual attribute or a column in the database, available for that object when using the model backed form helpers. We use model backed form helpers usually when we need to create, edit, or update an object.

By convention, form_for creates a form based on a specific model object. We are able to create, edit, and update that object's attributes. A form can be created by passing form_for a string or symbol relating to the object we want to deal with.

Here, the model-backed form takes an ojbect @product and infers the action and all else based on convention. Form_for checks to see if @product is a new or existing object. If its a new object, it routes the information submitted to the 'create route' by setting action='/products' (uri) and method='post' (verb). This can be seen by using "inspect element" in chrome. In the case that #product is an exsisting object, its is routed to the update route, setting action='/products/id' and method='post' (this works because there is a hidden _method="patch" which converts post to patch for rails to use). The information submitted is stored in a params hash that can be used for mass assignment, in this case "product"=>{"name"=>"some name"}.
Product.create(params[:post]) is equivalent to Product.create("name"=>"some name")

text_field can to be any attribute (column) or virtual attribute of the product model that is permitted (in products_controller.rb under function 'product_params' is where we set permissions). In the product model, attributes are: id, name, ingredients
-->
<%= render 'shared/errors', obj: @product %>
<div>
  <!-- there are 12 cols in row, if boxes take up 6 'col-lg-6', then offset by 3 'col-lg-offset-3' on each side will center boxes -->
  <div>
    <%= form_for @obj do |f| %>
      <div>
        <input id="form-input" class="form-control input-group-lg" autofocus="autofocus" type="text" name="">
      </div>
      <div>
        <div>
          <textarea id="form-textarea" name="" class="form-control" ></textarea>
        </div>  
      </div>
      <div>
        <button id="form-button" type="submit" class="btn btn-my-primary btn-xlarge"></button>
      </div>
    <% end %>
    <br>
    <%= link_to "Cancel request and return to products listing", products_path %> 
  </div>
</div>