config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  
  # Defines the root path route ("/")
  root "allergens#index"
  resources :products
  resources :allergens
end

app/models/product.rb
class Product < ApplicationRecord
  # dependent: :destroy, rails will destroy all reactions associated with Product when its deleted
  has_many  :reactions, dependent: :destroy
  # A has_many :through association is often used to set up a many-to-many connection 
  # with another model (Reaction). This association indicates that the declaring model (Product) can be 
  # matched with zero or more instances of another model (Allergen) by proceeding through a third model (Reaction).
  has_many  :allergens, through: :reactions


  validates :ingredients, presence: true
  #validates :ingredients, format:  {with: /\w+,\s/, :message => 
  #  "must be seperated by a ', '"}
  validates :ingredients, format:  {with: /\w+,\s|\n/, :message => 
    "must be seperated by a comma (,) followed by space ' ' or a newline (return)"}

  validates :ingredients, format: { without: /;/, :message => 
    "contains a ';' which is not a valid character" }


  # The model should be able to answer the question "Can user x do y to this object?"
  # When you write regular methods in the model those methods are all instance methods.  
  # In other words def some_method will be a method available on each retrieved product record
 
  def get_ingredients
    
    # split ingredients using ', ' or newline or '/' so abc/def is abc def
    ingredient_array = ingredients.split(/\, |\n|\//)
    
    # get rid of all duplicate whitespaces and characters that are not: a-z A-Z 0-9 - [] () ' 
    ingredient_array.map! do |ingredient|
      unless ingredient.empty?
        ingredient.split(" ").join(" ").gsub(%r{[^a-zA-Z0-9\-\[\]\,\'\(\)\s]}, '')
      end
    end
    
    # ingredient array shouldn't have any nill or all whitespace entries
    clean_array = ingredient_array.delete_if { |ingredient| ingredient.blank?}

    #x=1/0
    return clean_array
  end

  def causes_reaction
    if Reaction.exists?(product_id: self.id)
      return Reaction.where("product_id = ?", self.id)
    else
      return []
    end
  end

  def check_for_allergens
    allergens = Allergen.all
    # test each ingredient in product
    self.get_ingredients.each do |ingredient|
      reactive_substances = []
      # against each allergen category
      allergens.find_each do |allergen|
        # check for substances that match this ingredient in this categor
        reactive_substances = allergen.matching_substances_to(ingredient)
        #x=1/0
        if reactive_substances.any? # add information to the Reaction db
          # Create a new entry in Reaction db for this product
          Reaction.create(product_id: self.id, 
          allergen_id: allergen.id,
          reactive_substances: reactive_substances.join(', '),
          reactive_ingredient: ingredient.upcase)
        end
      end
    end
    #x=1/0
  end

  before_create do
    #Start with an empty db, there will never be more than 1 product in db
    Product.destroy_all
  end

  after_save do
    # Start with an empty Reaction DB, 
    # then check and save reactions after saving product
    Reaction.destroy_all
    check_for_allergens
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # Use before_action to set up an instance variable for an action, 
  # in this case, call set_product before calling show, edit, update and destroy
  # before_action :set_product, only: [:edit, :update, :show, :destroy]
  before_action :set_product, only: [:edit, :update, :show, :destroy]


# run 'rails routes' then add '_path' to the Prefix to get the url


#       Prefix Verb   URI Pattern                   Controller#Action
# ----------------------------------------------------------------
#     products GET    /products(.:format)           products#index
#              POST   /products(.:format)           products#create
#  new_product GET    /products/new(.:format)       products#new
# edit_product GET    /products/:id/edit(.:format)  products#edit
#      product GET    /products/:id(.:format)       products#show
#              PATCH  /products/:id(.:format)       products#update
#              PUT    /products/:id(.:format)       products#update
#              DELETE /products/:id(.:format)       products#destroy

# The purpose of the controller is to manage the incoming request and session

# GET '/'
  def index
    # Product.where accesses model layer and stores result in an instance variable
    #@products = products.order("#{sort_column} #{sort_direction}")
    # render 'products/index' happens by default at end of method
    @products = Product.all
    #redirect_to new_product_path
  end

  # GET '/products/new'
  # display a blank form to the user
  def new
    # set up a new instance variable which is an active record object
    # and pass it to the 'new' template in "new.html.erb"
    @product = Product.new
    # render 'products/new' happens by default at end of method
  end

  # POST '/product'
  # this is where you go after the user fills out the form and clicks submit on the form
  def create 
  # information entered on the form is returned in params hash 
  # ie: "product"=>{name=>"product name", ingredients=>"ingredient 1, ingredient2"}
    @product = Product.new(product_params) # create a new Product object and fill it values from the form
    # check for allergens and populate reactions db when you save product
    if @product.save # @product.save returns "false" if it can't save
      flash[:success] = "Product was successfully checked"
      # redirect must be a url, can't render a view template
      # (add '_path' to the prefix to get the url)
      redirect_to product_path(@product) # show
    else
      # validation error occured. We must render to have access to 
      # "products.error.full_messages" array to display generated errors 
      render :new, status: :unprocessable_entity
    end
  end

  # GET '/products/:id/edit'
  def edit # url will be something like /products/3/edit, edit form will be rendered
    # @product = Product.find(params[:id])... this is now done by set_product
    # render 'products/edit by default
  end

  # PATCH '/products/:id'
  #the general pattern used in the action create that handles
  #submission of model-backed forms 
  def update # this is where the form displayed in 'edit' is submitted using verb "patch"
    if @product.update(product_params)
      flash[:success] = "Product was successfully updated"
      redirect_to product_path(@product)
    else
      #for error messages to appear
      render :edit, status: :unprocessable_entity
    end
  end

  # GET '/products/:id'
  def show
    #already have @product at this point because 'set_product' was invoked
    #render 'products/show' (show.html.erb) automatically called before exiting this method
  end

  # DELETE '/products/:id'
   def destroy
    # already have @allergen at this point because 'set_allergen' was invoked
    @product.destroy
    redirect_to products_path, status: :see_other, notice: "Product was successfully deleted"
  end


  private

  def set_product
    # ask ActiveRecord to find the Product object in the db using the id from params
    #@product = Product.find_by(params[:id])
    @product = Product.find_by id: params[:id]
  end

  def product_params
    # use strong parameters to expose the fields we're interested in
    # require top level key be product and allow changes to name, ingredients
    params.require(:product).permit(:name, :ingredients)
    # returns {name=>"product name", ingredients=>"ingredient 1, ingredient2"}
    # To permit all attributes params.require(:post).permit!
  end

end

app/views/products/_form.html.erb
<!-- 
Model backed form helpers are tied to an object. There has to be a setter method, a virtual attribute or a column in the database, available for that object when using the model backed form helpers. We use model backed form helpers usually when we need to create, edit, or update an object.

By convention, form_for creates a form based on a specific model object. We are able to create, edit, and update that object's attributes. A form can be created by passing form_for a string or symbol relating to the object we want to deal with.

Here, the model-backed form takes an ojbect @product and infers the action and all else based on convention. Form_for checks to see if @product is a new or existing object. If its a new object, it routes the information submitted to the 'create route' by setting action='/products' (uri) and method='post' (verb). This can be seen by using "inspect element" in chrome. In the case that #product is an exsisting object, its is routed to the update route, setting action='/products/id' and method='post' (this works because there is a hidden _method="patch" which converts post to patch for rails to use). The information submitted is stored in a params hash that can be used for mass assignment, in this case "product"=>{"name"=>"some name"}.
Product.create(params[:post]) is equivalent to Product.create("name"=>"some name")

text_field can to be any attribute (column) or virtual attribute of the product model that is permitted (in products_controller.rb under function 'product_params' is where we set permissions). In the product model, attributes are: id, name, ingredients
-->
<body style="background-color:lightcyan;">

<div><center>
  <div class='form-horizontal col-lg-6 col-lg-offset-3'>

    <%= form_for(@product, :html => {class: "form-horizontal", role: "form"}) do |f| %>
    <!-- skip Name of Product on this form---------------
      <div class="form-group">
        <div class="col-lg-12">
          <%= f.label :Name %>
        </div>
        <div class="col-lg-12">
          <%= f.text_field :name, id: "form-input", class: "form-control", placeholder: "Name of Product", autofocus: true %>
        </div>
      </div>
      <br>
      -------------------------------------------------->
      <div class="form-group">
        <div class="col-lg-12">
          <%= f.label :ingredients%>
        </div>
        <div class="col-lg-12">



<%= f.text_area :ingredients, id: "form-textarea", class: "form-control", rows: "10", placeholder: 
"ingredient 1, ingredient 2, ...

ingredient 1
ingredient 2..." %>


        </div>
      </div>  
      <br>
        <%= f.submit "Submit", class: "btn btn-xlarge btn-primary" %>
        <%= link_to "Back to Allergens List", allergens_path, class: "btn btn-xlarge btn-info" %>
    <% end %>
  </div>
</center></div>
</body>

app/views/products/_product_allergen.html.erb
<% substances = product_allergen.get_substances %>

<!-- Panel displaying allergen and substances -->
<div style="font-size:x-small; background-color:lightpink;">
  <u><i>
    (<%= product_allergen.category %>)   
  </i></u>

  <% substances.each do |substance| %> 
    <% if substance.upcase.include?(search_item.upcase)%> 
        <li><%= highlight(substance, search_item) %></li>
    <% end %>  
  <% end %>
</div>

app/views/products/edit.html.erb
<h1><center>Edit Product</center></h1>
 
<%= render 'form'%>

app/views/products/index.html.erb
<h1>Products</h1>
<div>
  <div>
    <table>
      <tr>
        <th>Ingredients</th>
      </tr>
      <%= render partial: 'shared/product', collection: @products, :locals => {index_view: true, :search_item=>""}  %>
    </table>

    <div>
      <%= link_to "Add Product", new_product_path %>
      <%= link_to "Back to Allergen list", allergens_path %>
    </div>
  </div>
</div>
<br>
<br>

app/views/products/new.html.erb
<h2><center>Check Product</center></h2>
<small><center>
  <i><u>Enter ingredients seperated by a ", " (comma space) or a newline (return)</u></i>
</center></small>
<br>

<%= render 'shared/errors', obj: @product %>
<!-- would provide the @product object to the partial, available under the local variable obj -->
<%= render 'form' %>

app/views/products/show.html.erb
<body style="background-color:lightcyan;">
<style>
  table, th {
    border:5px solid black;
    text-align: center;
    margin-left: auto;
    margin-right: auto;
  }
  tr, td
  {
    text-align: center;
    vertical-align: center;
    border:1px solid black;
    padding-left: 20px;
    padding-right: 20px;
  }
</style>

<br>
<div><center>
  <%= link_to "Edit this product", edit_product_path(@product),class: "btn btn-xlarge btn-primary" %>
  <%= link_to "Check Another Product", new_product_path, class: "btn btn-xlarge btn-warning"%>
  <%= link_to "Back to Allergens List", allergens_path, class: "btn btn-xlarge btn-info" %>

  <br>

  <h1><strong><%= @product.name %></strong></h1>
</center></div>

<br>

<table><center>

  <!-- Heading: Check if product's ingredients cause an allergic reaction -->
  <% if @product.causes_reaction.empty? %>
    <tr style="background-color:palegreen;">
      <th>
        <h2 style="color:black;"><strong>No Allergens Found</strong></h2>
      </th>
    </tr>
  <% else %>
    <tr style="background-color:lightcoral;">
      <th>
        <h2 style="color:black;"><strong>Allergens Found</strong></h2>
      </th>
    </tr>
  <% end %>

  <!-- display each product ingredient -->
  <% @product.get_ingredients.each do |current_ingredient| %>
    <!-- check if ingredient for this product is in Reaction db -->
    <% ingredient_search_results = search_all_reactions(current_ingredient) %>
    <!-- if ingredient causes reaction -->
    <% unless ingredient_search_results.empty? %>
      <tr style="background-color:lightcoral;">
        <td style=" padding-bottom: 10px;">
          <strong><h5>
          <%= current_ingredient %></h5></strong>
          <% reactive_allergens = Allergen.find(ingredient_search_results.pluck(:allergen_id)) %>
          <%= render partial: 'product_allergen', collection: reactive_allergens, :locals => {search_item: current_ingredient}  %>
        </td>
      </tr>
    <% else %>
      <!-- ingredient does not cause a reaction -->
      <tr style="background-color:palegreen;">
        <td>
          <strong><h5>
            <%= current_ingredient %></h5></strong>
        </td>
      </tr>
    <% end %>
  <% end %>

</center></table>
</body>
<br>